
RESOURCES_DIR=$PCL_DIR/Localization

RESOURCES_NAME=BaseResources

RESOURCES_INPUT=$RESOURCES_DIR/$RESOURCES_NAME.resx
RESOURCES_NAMESPACE=CentroForms.Localization
RESOURCES_CLASS=$RESOURCES_NAME
RESOURCES_OUTPUT=$RESOURCES_DIR/$RESOURCES_NAME.Designer.cs
