
echo Working with $RESOURCES_INPUT
echo Creating ... $RESOURCES_OUTPUT

./resgen-cs.exe $RESOURCES_INPUT $RESOURCES_NAMESPACE $RESOURCES_CLASS $RESOURCES_OUTPUT
sed -i 's/using System;/using System;\n    using System.Reflection;\n/g' $RESOURCES_OUTPUT
sed -i 's/typeof('$RESOURCES_NAME').Assembly/typeof('$RESOURCES_NAME').GetTypeInfo().Assembly/g' $RESOURCES_OUTPUT
sed -i 's/<auto-generated>/<autogenerated>/g' $RESOURCES_OUTPUT
sed -i 's|</auto-generated>|</autogenerated>|g' $RESOURCES_OUTPUT

